name: Bug Report
description: Report a bug in the ArgoCD MCP Server
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure server with...
        2. Call tool '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Server Version
      description: Version of argocd-mcp-server
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: argocd-version
    attributes:
      label: ArgoCD Version
      description: Version of ArgoCD server
      placeholder: "2.10.0"

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      options:
        - stdio
        - HTTP
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output (ensure no secrets are included!)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (ensure no secrets are included!)
      render: yaml
